version: '3.6'

x-defaults: &defaults
  restart: unless-stopped
  logging:
    options:
      max-size: '10m'
      max-file: '10'
    driver: json-file
  networks:
    - converter

networks:
  converter:
    name: converter
    driver: bridge

services:

  converter:
    <<: *defaults
    build: .
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - redis

  redis:
    <<: *defaults
    image: redis:5-alpine
    ports:
      - 127.0.0.1:6379:6379
    container_name: redis
